# todo 切生产环境时，需要取消创建合同接口测试代码WithHoldApiV2类中352行代码和AlipayTemplate类中47行支付默认金额
server:
    port: 9090

h5:
    domain: https://axkmbtest.caixinsc.com #H5域名
    orderIndex: /pages/me/order #H5订单页面

admin:
    # 标识名称，应当是唯一，用于隔离同环境多套系统区分
    flagName: hy
    serverDomain: https://axktest.caixinsc.com/prod-api
    signConcatRedirect: https://axktest.caixinsc.com/prod-api/appopen/toSign/   #签约合同后重定向接口

#OSS存储
oss:
    local:
        #文件域名
        domain: http://localhost:8080
        #存储路径
        upload-file-path: D:/ruoyiVueS
    aliyun:
        #阿里云api的内或外网域名
        endpoint: oss-cn-hangzhou.aliyuncs.com
        #阿里云api的密钥access key id
        access-key-id: LTAI5tKVXmFmHVqeefqppcAP
        #阿里云api的密钥access key secret
        access-key-secret: RyjEP9HamWH18WYgXXC83TPi1GGeJo
        #阿里云api的bucket名称
        bucket-name: hlkdev
        #外部访问域名
        domain: https://hlkdev.oss-cn-hangzhou.aliyuncs.com

# 阿里云短信
aliyuncode:
    accessKeyId: LTAI5tKVXmFmHVqeefqppcAP
    accessSecret: RyjEP9HamWH18WYgXXC83TPi1GGeJo
    signName: 海南韵乐科技
    templateCode: SMS_305133326
    encodeKey: as8jhhg98sgsg#!@ #加密密钥
    realName: #人脸实名相关 https://help.aliyun.com/zh/id-verification/financial-grade-id-verification/user-guide/activate-id-verification-for-financial-services?spm=a2c4g.11186623.help-menu-2401581.d_1_0.126ff32dzv0bBO&scm=20140722.H_143097._.OR_help-T_cn-DAS-zh-V_1
        mapId: 1000012171 #场景id

# 阿里云ocr识别
aliyunocr:
    AppCode: 4a00c7baa2ef4355b2532949528541da

#代扣参数(v1)todo 已经弃用对接
dk:
    #代扣appId
    appId: 6B180037ABBEBEA991D8B1232F8A8CA9
    #代扣平台请求地址
    serverAddres: https://axk.caixinsc.com
    #代扣平台商户社会信用代码
    merchantId: 91460000MABXL9J664
    #代扣平台公司商户名称
    companyName: 海南韵乐科技有限公司
    #商户法人名称
    leaseName: 陈洁
    #商户支付宝uid
    leaseAlipayUid: 2088650322321594
    #代扣平台会员id
    loginId: BNOIPGVM
    #合同模板id
    templateId: T20241025164940003259

##代扣参数(v2-收单宝)
#dkv2:
#    verion: V2 #版本2版本2对应鑫雀服务商
#    plateform: 金享扣
#    #todo 代扣API调用token，在私有化部署系统后台参数设置中获取【认证token】
#    token: 2nHTTaj2Dxs2HYabcd1j1fRcesPSYTX2z5f
#    #代扣平台请求地址
#    serverAddres: https://hj.sk.zhaocaisc.com
#    #对应平台请求的真实ip
#    serverIp: 120.26.14.203
#    #代扣平台商户社会信用代码
#    merchantId: 91431300MAECT8J55D
#    #代扣平台公司商户名称
#    companyName: 娄底恒越科技有限公司
#    #商户法人名称
#    leaseName: 颜晟
#    #商户法人身份证号
#    leaseIdNumber: 432501198701011530
#    #商户支付宝uid
#    leaseAlipayUid: 2088960880372496
#    #代扣平台会员id
#    loginId: 15388903238@163.com
#    #合同模板id---正式
#    templateId: T20250429094257007123

#代扣参数(v3-云租界)
dkv2:
    verion: V3 #版本3版本2对应云租界服务商
    plateform: 金享扣
    #todo 代扣API调用token，在私有化部署系统后台参数设置中获取【认证token】
    token: AC3TFYNy7iJmCJ1D
    #代扣平台请求地址
    serverAddres: http://120.26.249.78:8001
    #对应平台请求的真实ip
    serverIp: 120.26.249.78
    #代扣平台商户社会信用代码
    merchantId: 91431300MAECT8J55D
    #代扣平台公司商户名称
    companyName: 娄底恒越科技有限公司
    #商户法人名称
    leaseName: 颜晟
    #商户法人身份证号
    leaseIdNumber: 432501198701011530
    #商户支付宝uid
    leaseAlipayUid: 2088960880372496
    #代扣平台会员id
    loginId: 15388903238@163.com
    #合同模板id---正式
    templateId: T20250429094257007123
    #CPS配置(此参数开通权限才会有用)
    promotionId: BNOIPGVM
    #CPS流量解密密钥(此参数开通权限才会有用)
    cpsAESKey: KnSphJnNqqTnOoOn
    #租户ID
    tenantId: YELWSGPG #沙箱环境

#支付宝H5网页应用配置(对应接入代扣主体的测试应用)
alipay:
    #应用ID
    appId: 2021005144647898
    #应用私钥
    clientSecret: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCxG5QhFIFKHBUqY1sDS0W5ud2mYjaP2o+DObPwpmluqrk5+bHlIv1laDM9hda8d60wsw1Qi2LHhH3cEunBOV/3tNoBMV0yiLH8FoV7ZEQdS+wKEZNwt4mkq5HQXySmOdlC8+ys3B6YJUWCQOWGv+u3H+wMZ3WxDIxTPLhk8e35fTr31CwXWhlMn7dPqSjVw/9BOGXNEnEyM0jQ9OxSJUPUQ6+blEEaDIKMYut5votjv96AbbTSX+mvtddMbWMTnmgeqZ7wZR0thlnX8JPGYjNpx8jSwXhlbqUVI2LFqjZWb9S86sHmHjQyOkvNZ+erY2h4p3rt/qUbkaGqT9cdqlPxAgMBAAECggEAVGgyZrmhDLLpm3QSsjUzm9prOprgKhsd/oqHqY+F/Ao9kNXh5LSSU7wff5jDyLq4vdb354UmpLQOT85rvX0csa9tntfp9OWU/fG12CLnG5dNfVb3D+dJIEPskIRnsRks5G3gRFn78sMAp51KRrg9HN+H3jmIq8KxNhJgRyvOIPKyzf77cd5BjAf9Yd1yBZtIV/S+hKifrCrixOw9UFR5D7nN0XnIZThAsGBnpMrCWFBdkwbMB8XLV3AAH2pmcAF7w2pBCn5/NUx08oguEZs8sFZcKSjIX0PZSuSQPolZQQzwqMRxSsafxQHw5XOaWioObfXTkaDEh3XUtbQ1WtYK6QKBgQD4At0tIbHvEu+2kF0h5FDGKqw5SZV8fOkxi/hL6BTvzuHxBlvGzRLZWXFIlaMfjO6nz00lcLOEd7Ohd9tmm8IchVXvUl3hvNvR7JwGVHAegFehq/sO/W8bXvmCXmqwwBrrll7u4oRZiVkJk+G9UYH8UNaNu4UuxlWqiH6Tei/0KwKBgQC20AjV34/5fQgAiQw6lkPRDUKzBKJo6EgVVjT7UmUZJ4DxY4nd9U2sNcVT1k0pr+El4NenigygQQvWEh6Rjb65rtEy5djcTOJgt4mX57sMzRZJJznuym7FqzslFBOTVlFbIRhKSqFCT9KKAxCAoEyGh9+aAp9PnLwi1ok6NFN+UwKBgAbGHUBkUTXUcJOt8b1BPSuMctPFvL1/s+bUid2Y4ymBnw40PEF7zG3/UWbIH4J3GPWgZd0F7QFLO67HVUjCLFUXFzfIKiRGQkLDkadimwVaQAp8ZgkMxwIaX/o9lfBp7tJMcx9XNII1jCcE0P+YwFIh6xpH6uVSKXjU7ZAdoD2tAoGAQYTNpdk6AHCPLaHwgA7av1HBVeeTTYXyT7NVybz9/sXpsJm8D5CbBd0/m4xymz4tsyWiJKmVXNnzJAXabtAeSu4ci+FUl5/2gjNFXOvwXeYi1pT4blye1rlHuUI4wdVt0vtJeVbF9L4m9s+iWncY9h48RTYrYp0J0HKTPAkE44ECgYArGSDPbuJbcaEeKYi1Iz2Er+kPPpuueTn/oChPZuedv26HWamWgaF3dLIBIzuBIwG6YzvvPN2JNh8qIS1D45DcEHhme24i4NCuab2rKcx2Mail7Say2ScJcMxlrcfPZLDy6fPLPo30vcWRejG0juPjGF9JqDseJ94ufmG2vRxIug==
    #支付宝公钥
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoK61fRtp+VJ5CbQ3Q6SVVPI0axLx+Rc9uNgx99LaGsJGbthfFsR9thpx/F8ameV4lW/nPWrJMl+VZIHzFWwM12yAwC8EC9jKUr5EGIcQRUgoHeT6zLCXoRX2ogWXO+iDNkweBuBfK5lQ46KCRFkQVEnphyu2NHLhy+vFEJw0ImzvOfzUX8pW+qTJ7X+pHWbGBbNuwrop5MAo8G/eW7sPTYcJb8sOXUpjpqeEqfzIFRl7IqMuNSAkTwbxQRo6DriZ6wbtJx2tMJX7MLM4GT8RbQBwxu04xPH0VQ3HGrf2tbxwt6IuzvFEWdlzJ9HS2otPBX9b9hMtnWt2nw+/wAeXcQIDAQAB
    #授权回调地址（支付宝授权登录回到地址）
    redirectUrl: https://axktest.caixinsc.com/prod-api/alipay/oauth/callback
    #支付宝网关
    geteWay: https://openapi.alipay.com/gateway.do
    #异步支付通知地址
    notifyUrl: https://axktest.caixinsc.com/prod-api/alipay/hlk/order/notify
    # 页面跳转同步通知页面路径 需http://或者https://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
    #    returnUrl: https://zhbexg.natappfree.cc/alipay/return
    #签名方式
    signType: RSA2
    charset: UTF-8
hfb:
    # 汇付宝公钥
    hfbPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1Ayv5x8tYQIQcyCIOgQVK0qhMiG+82R9c/pVeSTDfkaLbNOg470Osr6Dx3NFge/tifPaw8DwFqcSYvTT3iLykNpyhGBIFKvApnEIom6HeSIR5FyLurw+ekacBnffXquRBPF9dKVv+a59X4VSStH9ofeRIXYPM7Uq2RxddExYX6RvVwfYCLrkdRntaKD6xdZW4a3WLhSJoWiBrsB5c8opXFvKIKkvkH8Js8QIUbgakKJ6g+3RG/h+CvpE2PmFVrV06KdrVqGNpvzKhIWzwNYLrAMbSFpE+jkZr6vnpMFm1uVUXMPRcefzxNyeX4LYFCg80LNGKS8un2v/6aBlGXfjjQIDAQAB
    # 商家公钥
    merchPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwcrEHCkmcaxSSq5H3uJAdrXgwrqpDa3xxVAg65EU5hhHVlo0RRuyI5fAxdElLEqPIdxC7uvX20iqbtZT3p4/Yv1UDtcl6fKfhGz5PeDzxV/yH/yal/mxTzhH8u4RIK3+59mkl4c3SVF9TZXSPxD7CA5zrXn3f+T6/1bF+jfVf7CQ8jl3XZGwOBr+ndt113uJnVdEQxlK3/DjPc22is9hDacz1HvOF6HmXPWGAinJMAITYoxEqVItzFsWXwAvumn2upd/IEZ0ucktAB1ZR+4hSTdKPEg3UZRxA/3VCMWN4Tg8kDV5m1B21bacPz4mZ19Dgp9vJgxaiVni0yLIHFkCvQIDAQAB
    # 商家私钥
    merchPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDBysQcKSZxrFJKrkfe4kB2teDCuqkNrfHFUCDrkRTmGEdWWjRFG7Ijl8DF0SUsSo8h3ELu69fbSKpu1lPenj9i/VQO1yXp8p+EbPk94PPFX/If/JqX+bFPOEfy7hEgrf7n2aSXhzdJUX1NldI/EPsIDnOtefd/5Pr/VsX6N9V/sJDyOXddkbA4Gv6d23XXe4mdV0RDGUrf8OM9zbaKz2ENpzPUe84XoeZc9YYCKckwAhNijESpUi3MWxZfAC+6afa6l38gRnS5yS0AHVlH7iFJN0o8SDdRlHED/dUIxY3hODyQNXmbUHbVtpw/PiZnX0OCn28mDFqJWeLTIsgcWQK9AgMBAAECggEBAJcX2Yk/SDsOqOaTNXQAoVQtAD2zPUVuHnfBvrkL1+iCe3RHRkOvkVeQ5PsW0s3SoAA9dG5FsXnGESPztVZ3uWIbs6MSefwKb/bW5Akrz8ROxz/LOllNk8H5VpeAqBf7sSfhmCOQiDmA8JpCOrdzLNYeNnDGDINJ66yTYi5xw+MWT4AEYKZuy4r/gBuWFfJol9GbyQuSRcY76rhEOJSyJPU0/mhSoSZgCHukCtRbFZtexdF/Z4asuQZL5E6N4DwWLcMtpyo5LFWK+So9I4/ibkHpgWN3Jvfz1cfdGKLsD2S5hWU2qM20wMbluDcc+7QAU+H68NLpB07wQek1AxgTol0CgYEA/5FhMJwWW7z0YiQgHBxM1SnCsFPR8b0olqjbibfdsO+vH1B7TOU+TIxUYU+JV7RgxJ2Ty7UbPiEaknia2BXS9nm/6nknfROjv71Z6uO30a/ENpcx1B5QT01oYOZ0AYUFK444ro1oLpMJpHKmb6iCHN5bDwDevTK9AuFShLThMe8CgYEAwh6ls4kbKqsAep857rfrDXrFlpQGBmlzfR+hWm+pJhUmzRIAoKe0Q4m79b8Oopl2lfde8YlA0AUrFtA0j24rFatqF/zWMr1C24LzdXXnHGPB+AysUmvFUqsPrVGqUf5qjrZDzlL2p10PrlUNGI1qC4KzUJHT1oDlIDoBD1lYkhMCgYEArj/lUEtcQzhWOAQBkKkLCdvrTmYYIwaiAfcnmIKwuM7zTBqHtyomi/KyJZchQZdO0z/NYXseFAJmJ6/rg6F9sWfZnnj0n6cgYr8r66dP0bxRwBbedo4km61fmZIHTnHv0H6rzvfDLN48GM/DAyaVcDF7TIN/WuiZTrlqlejuEikCgYBzKLlGg/zw2Bdlp1Y37zXrfjz/snrMjPxtazlOrFVdeUjWeWqT5EmFk41FIX3uKjp2hxT1F2aywY4pb4Tu3f2DUniTGHR+D1c9YDdMJJDhf7DPlb0Y/ERIYaDgQkVXdSYD2c7p9L/M0+F8m4o0WZhikbwM/SX95+OFtcNxNqDbrwKBgQDHxsCKdSDQkVeSaMWvzbOOyh4pSy/Jrs8pPV2zl7zkVHB6p+OQgwdcgu9kX3yZMde2aqYeKUWwZ/aUGSdF3AEYlFy4sIy3zcjqDCA9RrjS4sirRn174noilowX9SahIkjf1X4nh9Lo/2mIL74j2+A65Q3d1E2hroN3g/9Frg0g6A==
    # 汇付宝七位商户号
    hfbMerchantId: 2297902
    # 汇付宝接入备案域名(todo 使用建交域名代理jxkhfbhd.caixinsc.com到本服务)
    hfbHtDomain: https://jxkhfbhd.caixinsc.com
    hfbH5Domain: https://jxkhfbapphd.caixinsc.com
    # 异步通知地址(todo 使用建交域名代理jxkhfbhd.caixinsc.com到本服务)
    payNotifyUrl: ${hfb.hfbHtDomain}/prod-api/hfb/payNotify
    # 签约通知地址(todo 使用建交域名代理jxkhfbhd.caixinsc.com到本服务)
    signNotifyUrl: ${hfb.hfbHtDomain}/prod-api/hfb/signNotify
    # 签约返回页面地址(todo 使用建交域名代理jxkhfbapphd.caixinsc.com到本服务)
    signReturnUrl: ${hfb.hfbH5Domain}/pages/me/payStore

### 衡阳尚签WAP收款
hfbAliWap:
    # MD5密钥，商户后台网关密钥下面第一个
    key: 4E423BD52A034736B2AF972B
    # 商户编号，（汇付宝商户内码：七位整数数字）
    agentId: 2372141
    # 异步通知地址
    #  notifyUrl: https://axktest.caixinsc.com/stage-api/hfb/payNotify
    notifyUrl: https://axktest.caixinsc.com/prod-api/hfbAliWap/payNotify
    # 同步通知地址
    #  returnUrl: https://axktest.caixinsc.com/stage-api/hfb/payNotify
    returnUrl: https://axkmbtest.caixinsc.com/pages/me/payStore?orderCode=
