server:
  port: 18080

h5:
  domain: https://axkmbtest.caixinsc.com #H5域名
  orderIndex: /pages/me/order #H5订单页面

admin:
  # 标识名称，应当是唯一，用于隔离同环境多套系统区分
  flagName: dev
  serverDomain: https://axktest.caixinsc.com/stage-api
  signConcatRedirect: https://axktest.caixinsc.com/stage-api/appopen/toSign/   #签约合同后重定向接口

#OSS存储
oss:
  local:
    #文件域名
    domain: http://localhost:8080
    #存储路径
    upload-file-path: D:/ruoyiVueS
  aliyun:
    #阿里云api的内或外网域名
    endpoint: oss-cn-hangzhou.aliyuncs.com
    #阿里云api的密钥access key id
    access-key-id: LTAI5tKVXmFmHVqeefqppcAP
    #阿里云api的密钥access key secret
    access-key-secret: RyjEP9HamWH18WYgXXC83TPi1GGeJo
    #阿里云api的bucket名称
    bucket-name: hlkdev
    #外部访问域名
    domain: https://hlkdev.oss-cn-hangzhou.aliyuncs.com

# 阿里云短信
aliyuncode:
  accessKeyId: LTAI5tKVXmFmHVqeefqppcAP
  accessSecret: RyjEP9HamWH18WYgXXC83TPi1GGeJo
  signName: 海南韵乐科技
  templateCode: SMS_305133326
  encodeKey: as8jhhg98sgsg#!@ #加密密钥
  realName: #人脸实名相关 https://help.aliyun.com/zh/id-verification/financial-grade-id-verification/user-guide/activate-id-verification-for-financial-services?spm=a2c4g.11186623.help-menu-2401581.d_1_0.126ff32dzv0bBO&scm=20140722.H_143097._.OR_help-T_cn-DAS-zh-V_1
    mapId: 1000012171 #场景id

# 阿里云ocr识别
aliyunocr:
  AppCode: 4a00c7baa2ef4355b2532949528541da

#代扣参数(v1)todo 已经弃用对接
dk:
  #代扣appId
  appId: 6B180037ABBEBEA991D8B1232F8A8CA9
  #代扣平台请求地址
  serverAddres: https://xxx.caixinsc.com
  #代扣平台商户社会信用代码
  merchantId: 91460000MABXL9J664
  #代扣平台公司商户名称
  companyName: 海南韵乐科技有限公司
  #商户法人名称
  leaseName: 陈洁
  #商户支付宝uid
  leaseAlipayUid: 2088650322321594
  #代扣平台会员id
  loginId: BNOIPGVM
  #合同模板id
  templateId: T20241025164940003259

#代扣参数(v3-云租界)
dkv2:
  verion: V3 #版本2版本2对应鑫雀服务商
  plateform: 安心扣测试
  #todo 代扣API调用token，在私有化部署系统后台参数设置中获取【认证token】
  token: ACz3EK4m8sEW6VuC
  #代扣平台请求地址
  serverAddres: http://8.153.175.191:8001
  #对应平台请求的真实ip
  serverIp: 8.153.175.191
  #代扣平台商户社会信用代码
  merchantId: 91431300MAECT8J55D
  #代扣平台公司商户名称
  companyName: 娄底恒越科技有限公司
  #商户法人名称
  leaseName: 颜晟
  #商户法人身份证号
  leaseIdNumber: 432501198701011530
  #商户支付宝uid
  leaseAlipayUid: 2088960880372496
  #代扣平台会员id
  loginId: 15388903238@163.com
  #合同模板id---测试
  templateId: T20250429092212007122
  #CPS配置(此参数开通权限才会有用)
  promotionId: promotionId
  #CPS流量解密密钥
  cpsAESKey: KnSphJnNqqTnOoOn
  #租户ID
  tenantId: UFDOGRRM #沙箱环境

#支付宝H5网页应用配置(对应接入代扣主体的测试应用)
alipay:
  #应用ID
  appId: 2021005127611313
  #应用私钥
  clientSecret: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCAy9BsTS3DVoe5It2MA8tJXhFspfDcRLEy4Ru4AVAEj0AL4MjhWXKNHZySBhMMzdgZs3+SrV1rt03TZJQYEgoeRJPZIRpAy/NtY3v4JPJqK+Dccns4ZrENo7aFUWsOduKRglQRuUwxr7MllhvV7T4JAregOVzstFWNByQeHjn1OG2COJb0z/85/g/KprwvSCFlq/049VrLXJ3jhlJaPK7qmAhg65eunYrKNXTWGulaoHjzj+kOfSi26XMSoPV5JRk/GHZEbLR9rfBbX+7lQhTKnzXs0cEN6Dij+AmbemkwrkzHxvNZvqSZ1ZFMUk1wOXaek3BCBapzS2fnmbfUPpYRAgMBAAECggEAdINsxjy/lIG4AGSpFVvtUC7YBnjLvwgpYUTBhaEyWR2aK+Sq9Sms9jn+hR8XprKktwNp+i/5XlOSBRVs36WaH62cLoXCsTGPwrqH0IDkB+Yv4l1yWSCVNSiQGmUAOzKTXl0PXoVJh31RzEPSZKHdR9t8cGbUSJIO/qiiJNjlR47+tzUislxm/n+kLMFMcnlJAWdhPmKw6gTkc5ic8d2Qv20qwcHdgUkV8PNjDBPwcSEboHMgDaYDQBQsvBodZyZQE7cb7iB9IIKRIwOhNZJM7LVbNA69WrnLYu3b5N5+YPpIUwzuVk8YpDegbclJBpOsMo9KJaIzDC48pu6HRW9okQKBgQC9XRNwTF9sP1pzV8/5yTqCD5J4aflOrw4aFRTFfJdSljVPrrXeOPoKPxj9wNaJ5mop73RjmkWpyePZSZvCEO8Fl0hKvFIm9GSRZT4QoQnNw/TM/hqukuoo0rzK2mUiozwBEHpDAde730itg1PIQc5xxytePrCymhKaGSf2Kxbl9QKBgQCuHnzI6H8cehTdTqb2eXWY5knMtDIzvOf3FNXAPTI/1Lzn7kq2iAJWP6cxdT4rhXXIs/H/WOADlRjsquqAJSH2cKDrgO8fHe8xBRzEigJVygbufXajNVwtDAG2kPzfphPi3HEUP1XLhULSGeoUaeC+yRlVUm50SWW96mBn7dNCLQKBgQC4rscflgzWuO8RYUpANkauxFs4vzpbyBU70OWiOgInlMHHxgAwDGeoiKNqEKHsemF+JsDfx307u+BRch3L5tIHJOVnpkWFIoPW3ePrOfQiz4O4Tfdd3YEscWOZf+h1ILiL3TMwmOJ7o6fxOg0DWVLr2rDsSL3yYpvT2McFqj655QKBgQCgIuX9GOce16Cs0RN5h8eB8fpZzDiHoOtuMLlN7npyfkOmw1/vdDNCA5TPRdcBy+LBzc15XNHaOZwMvjyh0oTj1D4Lmi9R3QQJf3wvvgXbxMyPNtCP1hmKTIqez8XiIyoS8U8GoiFT5qHH/ZFtaNsMXINyFzgCtyZdfltf+jjbmQKBgDdn42SwHXOmi7XL1Iz5I6ZcgSpzdU7ROhEsp8YTlQxGC0Ba9z5QG1AYoMhrd85eAuXt6nXsjSUdCRJfzfOlMpykOGrBZae41IV5wGGUlarq6umgXw1gvCY03u3OEbWNfsnGwpkGx2EBN4pNIyLK/CpTbOj20bXVzt4gHt4Jstx2
  #支付宝公钥
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtmQQ5W98jHkR6vpGcmSOuACIUAGkDmSUY11f0Y8Z1wJvxQV+Gy8cz2v/HPsyskqk+YwHe6ZINvQcXHE7qXKpVib4VOhjBMMeuEYeuYiEPdva+9N5fO36DuFqa4hbY9tT6Mec9Lv9SJ/w7F0VjGSgwJWn4ad1meuzSnxeaj8XPjwhkf4kvSXUQLZ4WF0ikBUHmPdNP5LXYohkwz3OT0q7bo/PfDem5IdoyGvPT0E0rMLhyNLpIGjoBN7Q4pOvQ5zzz4LiG664mcikdpBA8Uty/mUklt2uaudZIX+VkuOBzGMdMQH7I26gXIVZG7WcJPr9BYCvhYbbaB6W58xaD1+hdwIDAQAB
  #授权回调地址（支付宝授权登录回到地址）
  redirectUrl: https://axktest.caixinsc.com/stage-api/alipay/oauth/callback
  #支付宝网关
  geteWay: https://openapi.alipay.com/gateway.do
  #异步支付通知地址
  notifyUrl: https://axktest.caixinsc.com/stage-api/alipay/hlk/order/notify
  # 页面跳转同步通知页面路径 需http://或者https://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  #    returnUrl: https://zhbexg.natappfree.cc/alipay/return
  #签名方式
  signType: RSA2
  charset: UTF-8

hfb:
  # 汇付宝公钥
  hfbPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3jSzrlNHBuZEME7Mbg0RFcgNvq6VCcx3UEmjLkWO4PdCHLTNP27a4+fjtbyndIPLYDe52SbiIq6SY0LUG0xLR0o1aXESVxpp/04CXuURhlsngmkzFqetkey60QhXKWWf+bC8EnLbcew9Z49yAgwPjsiAOikMZ8Yq8WBH+6iza8EnVGXGrH6Et0Qv5CheTUZY1/sgMg+2niCpJQxDTviQGmmhIJZM8an3/nq0insbqARmiIseLlqFloiuhP54o8tP3z2ddCloWWzd+ZtuWG9AOd+vkZNkiDM4oex934oR/G7qbNBa5i6hIKZ3JJBVkGnuVA7tftVCRCsqCvgwpL6R/QIDAQAB
  # 商家公钥
  merchPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuV5EeYE0YFiwFHsgr50GQOKXWemslfEfv/ys0Iw1tfEhGhW/4PvW+I1+rclp4hF1mIV6x18k2yOmb8pEaQ9h3zKNQb29TiiFWWChvXISZnHpBirn25kOD8bqMu9iPEIYvM5jtvaUThO5zOxB4IdWmLXKSSAZqvWbnPAXXSJOreAsaOjTLR0m4M1wnKsOu8wkQ8n/Ji2SHPqOTm8zWam6gMA+20VHLQm2JVLplzSWAc20N2jUMWaMNRg8Nt826qj4EVSN4l8jV+RVoqUzFIBg6aOsAxd4Tk9WdMUXbQXxJHU+lMq7kShm21og3fa6Gu+VuJpZrzNMu4O2YblZKGiZ+wIDAQAB
  # 商家私钥
  merchPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5XkR5gTRgWLAUeyCvnQZA4pdZ6ayV8R+//KzQjDW18SEaFb/g+9b4jX6tyWniEXWYhXrHXyTbI6ZvykRpD2HfMo1Bvb1OKIVZYKG9chJmcekGKufbmQ4Pxuoy72I8Qhi8zmO29pROE7nM7EHgh1aYtcpJIBmq9Zuc8BddIk6t4Cxo6NMtHSbgzXCcqw67zCRDyf8mLZIc+o5ObzNZqbqAwD7bRUctCbYlUumXNJYBzbQ3aNQxZow1GDw23zbqqPgRVI3iXyNX5FWipTMUgGDpo6wDF3hOT1Z0xRdtBfEkdT6UyruRKGbbWiDd9roa75W4mlmvM0y7g7ZhuVkoaJn7AgMBAAECggEAFGeKBg3w5AIfL8H18R7Jx26p1l3gf4jRQ+Leav5kEyj9yc9HFc7i9O0uWpbnLtlZJnba8wNIHU8pTPjo2t+0mEsKPYhTRD01oIcAhsf9uoUjb2hdqVCJubbdpMmw+I0WCAJ3+3XdEVMeiq4e+kYrhBfOson0CVuLy5SqHbhfDMiF6SzRiTFMAELos7SwfjXZ0VAclGP7do/XWyUp2b2l9Z0nnaeKU2ecNBZlDXKcpsZ2Omz8HIXyJpeKooN63DSkjobPm6+/saNAL5118ZC8SxnvbZ61gsEk8/feHoYr58g6zgllLEb5uR7DJjmxrCF/bMqGv2OQ35s0cnPwUds/cQKBgQD7JACTjg2D/mvBSeZxsmOiLqJIoxeUOlH7OliPe6uF9XAJat2LJCpN5UPbUqgBC280SvzhJG103WeZIBNYiRqxC0qQUw1qUkpavJ1TkYw7lO5m/9b5TebQ05qTiBWd1DmJYbXfPQRjwjAG2/MkGIvdnZ43NhqnQeNXUHtr7T1RrQKBgQC89HgDymVmgHo1Ffc1z1cMOdnJzIXr6O3Gtj5Zhra+98qqKT/HAIAIhKsn9zNLUGT+XbkB1J5K68A1JlXc1LEZIiq0TEXAEerTH3XlplhdZ8qvRnVm48hqwyIQ+ZTllzOYloH5cHQkBsPkCIN7rz0N+P2SC7cw5Uo1Rr3vS+8fRwKBgC8lSBJrNXBU/8eOZvtrILceiAqYy2FhPWirQFrXPZDtTXYHIMXxKRvscTuoHa/shJjNhwGBBCdPNRaS5e7V9jPMSdgkLz2JaznzdJlulmPNBqBBYQr2K+GCB9+wSVaSs6ZtuGXLH5rWpotzGQbqsL8OytfUiVZi0RngGvtc0wkVAoGADb5+iFANhiIsQXZCkBBv1XzTwaD10M4VlZGmAV8SJdviSvRLJk98AKKdzH9npL/JSNNKZL6xcOOrDHKoZjK2WwyoLIsru6fR+99a9QRfgxPMo2ktmvlQl6tv6+orkXOpFh1EgP9UA1bWotyXq8R4XW7SCvB9N7pF5pApuqE8WHsCgYEAvKir/VM1K9Qhk78EshIXygL9F8LQxhpRkquZ3w/81fchn+/xLJv6HHpGLaGywAPM/kONcDkvJFLmHJDQ2cwLgrX2x0bUFRxNjQ0RLT7zjIuJq/WxECLVh6xDI8yGqT6OU0wfMEzinzm5eLaIwqRQLZoI0Qxvvn0nBjSh6/+iJD0=
  # 汇付宝七位商户号
  hfbMerchantId: 1664502
  # 异步通知地址
  payNotifyUrl: https://axktest.caixinsc.com/stage-api/hfb/payNotify
  # 签约通知地址
  signNotifyUrl: https://axktest.caixinsc.com/stage-api/hfb/signNotify
  # 签约返回页面地址
  signReturnUrl: https://axkmbtest.caixinsc.com/pages/me/payStore

hfbAliWap:
  # MD5密钥，商户后台网关密钥下面第一个
  key: 651886F030134F848F548A12
  # 商户编号，（汇付宝商户内码：七位整数数字）
  agentId: 1664502
  # 异步通知地址
  #  notifyUrl: https://axktest.caixinsc.com/stage-api/hfb/payNotify
  notifyUrl: https://axktest.caixinsc.com/stage-api/hfbAliWap/payNotify
  # 同步通知地址
  #  returnUrl: https://axktest.caixinsc.com/stage-api/hfb/payNotify
  returnUrl: https://axkmbtest.caixinsc.com/pages/me/payStore?orderCode=


