# todo 切生产环境时，需要取消创建合同接口测试代码WithHoldApiV2类中352行代码和AlipayTemplate类中47行支付默认金额
server:
    port: 9092

h5:
    domain: https://axkmbtest.caixinsc.com #H5域名
    orderIndex: /pages/me/order #H5订单页面

admin:
    # 标识名称，应当是唯一，用于隔离同环境多套系统区分
    flagName: yxk
    serverDomain: https://axktest.caixinsc.com/prod-api
    signConcatRedirect: https://axktest.caixinsc.com/prod-api/appopen/toSign/   #签约合同后重定向接口

#OSS存储
oss:
    local:
        #文件域名
        domain: http://localhost:8080
        #存储路径
        upload-file-path: D:/ruoyiVueS
    aliyun:
        #阿里云api的内或外网域名
        endpoint: oss-cn-hangzhou.aliyuncs.com
        #阿里云api的密钥access key id
        access-key-id: LTAI5tKVXmFmHVqeefqppcAP
        #阿里云api的密钥access key secret
        access-key-secret: RyjEP9HamWH18WYgXXC83TPi1GGeJo
        #阿里云api的bucket名称
        bucket-name: hlkdev
        #外部访问域名
        domain: https://hlkdev.oss-cn-hangzhou.aliyuncs.com

# 阿里云短信
aliyuncode:
    accessKeyId: LTAI5tKVXmFmHVqeefqppcAP
    accessSecret: RyjEP9HamWH18WYgXXC83TPi1GGeJo
    signName: 海南韵乐科技
    templateCode: SMS_305133326
    encodeKey: as8jhhg98sgsg#!@ #加密密钥
    realName: #人脸实名相关 https://help.aliyun.com/zh/id-verification/financial-grade-id-verification/user-guide/activate-id-verification-for-financial-services?spm=a2c4g.11186623.help-menu-2401581.d_1_0.126ff32dzv0bBO&scm=20140722.H_143097._.OR_help-T_cn-DAS-zh-V_1
        mapId: 1000012171 #场景id

# 阿里云ocr识别
aliyunocr:
    AppCode: 4a00c7baa2ef4355b2532949528541da

#代扣参数(v1)todo 已经弃用对接
dk:
    #代扣appId
    appId: 6B180037ABBEBEA991D8B1232F8A8CA9
    #代扣平台请求地址
    serverAddres: https://axk.caixinsc.com
    #代扣平台商户社会信用代码
    merchantId: 91460000MABXL9J664
    #代扣平台公司商户名称
    companyName: 海南韵乐科技有限公司
    #商户法人名称
    leaseName: 陈洁
    #商户支付宝uid
    leaseAlipayUid: 2088650322321594
    #代扣平台会员id
    loginId: BNOIPGVM
    #合同模板id
    templateId: T20241025164940003259

#代扣参数(v2-收单宝)
dkv2:
    verion: V3 #版本3版本2对应鑫雀服务商
    plateform: 云享扣
    #todo 代扣API调用token，在私有化部署系统后台参数设置中获取【认证token】
    token: ACwQwYj32DDQycRR
    #代扣平台请求地址
    serverAddres: http://120.26.249.78:8002
    #对应平台请求的真实ip
    serverIp: 120.26.249.78
    #代扣平台商户社会信用代码
    merchantId: 91430104MADNG7XG9M
    #代扣平台公司商户名称
    companyName: 长沙盛宏科技有限公司
    #商户法人名称
    leaseName: 杨婷
    #商户法人身份证号
    leaseIdNumber: 430223199308312227
    #商户支付宝uid
    leaseAlipayUid: 2088960885681430
    #代扣平台会员id
    loginId: 19073199452@163.com
    #合同模板id---正式
    templateId: T20250821113127008170
    #CPS配置(此参数开通权限才会有用)
    promotionId:
    #CPS流量解密密钥(此参数开通权限才会有用)
    cpsAESKey:

#支付宝H5网页应用配置(对应接入代扣主体的测试应用)
alipay:
    #应用ID
    appId: 2021005183697201
    #应用私钥
    clientSecret: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCHIWVL+pNwIXOKUujTNu7mrDiNMmwGPp2sIHI9btE2MCqVt98t1HcRT/7Fc1v363a/YjZKydelrDusG0GRj8mJwiTD6EL3jCQdQuv1NxFyYgZ/2tpJzeL/C51Ok4cZ5mY75V4a3JV9OXjOFjqxI54Sh36fzo7cnbu4VeW6UMK0yQNuH8uU5eG0J03d6hwLL1iUn42WNoaePaYFjV6YU2PgmN+fLMxbudV3fP2SuVmZ2VkGyIoTcWIAwk+O7TDX9U9gaa8oPQNwFitJsDxFOaP3BvD1ELUAGQ9AYEU4Q8wDgf0lnrVkffF84yI1P0HdW+4SBeTP7zViceILC5zrynCdAgMBAAECggEAVxFShoEezKoRGzhOogEML38aNQgfCGsCBu0lDqY/kQ258pv15j62tWX4v1qUEIscCTaLyuaA11PBYyRwvAyMjAGW1M/rjjsy7dO321kvGadFjs4BxnotX64pHn76FtsYVlF0sBQfEf+c8hTqnkZXzJKXKPrbnBTZ5m0aR1FQE1Fd4Sd3KccsZc8IwjSWXi8sibDotGReb3XWKPspt0E8W5+IdAwk2Q7ocSYb1l5f54pGunF3+B68ZaapMDc0k72+4JbomPDSBWM+u08KcBp4djmguuKTHMyeVTNk3xhFWyfD2QrqRi9QObnh9orHaB8luLXmeFctq7yTBVnOHyV4QQKBgQDADCLWKZTO2IGzowI1MUZOniP/eNZm/BxjxFCopYv73kjgxhK+NDAZmoWOfwjm5j7xolGkPxQ90zEePSiC8yXgpkHjKxzPkPwOg+968ymBb83q8UE5scljMgSNcayzHjndx6ZZEuUa1B900KtjQKafDDy/69bZtXkf00E/Q+1oTQKBgQC0ISRO6XTdjQB7Rg8IEy9tB851AI3V7UQ8Slv1Y7w2FFGVWflkLgCJfV7BtimGrY08DCa2iFq2lApv32vul8Knt+txnEBC3mjFsZ7wsqm68MtJdnyBLynzWhL62qHDtARw6h+ytVbdPJ2Ch1RK8Wv/BFt19PgZgRoohckF7ppRkQKBgF9KJkbpXuK7Xq/JZCEMj/wWT3pFdOyoj1WZZQQpECorAzI0Vbx2nJ83oqkvszUObZDrn2LFwb9jeO2uHtnK17J+DBcxnxwGrmptYHg7Cw8kcKHwjxKXentzp/qeurgteTzoAUwVKgSD2A/YMhIPVB16rvHzjSl899qosak4hSXJAoGAGI1v6oWt1UkT6Lmq8NnUnBL1VENoEeHObD1ifXdDv0dTu3zRHpOapSL+mH7g+CeN2cJ6QGUjoEFbjtYwWww6jyvlns3CgJraQyAr3vkrY3zQ6MmKvP0VxcLgVWsZo5hVBqMTAQPwvCU3/wO9PJ3dr5wDb3ednbRYQW/C79kPFdECgYA5J/dV83qfqe5aBtRrc3Mags3kOUJPQKXl3EILRTqEONfRZofknmAQKwsNj7ocqcSibSkUcYXF5+vRxNNZUZMPiPv4+RtGXk8aijXeEv0XLGaAEk0jLxVds5wkwlkaEmgF/mpSaK4diOAFRSekHVrfLkH1IZ90CABUvNqy8kyWpg==
    #支付宝公钥
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtmQQ5W98jHkR6vpGcmSOuACIUAGkDmSUY11f0Y8Z1wJvxQV+Gy8cz2v/HPsyskqk+YwHe6ZINvQcXHE7qXKpVib4VOhjBMMeuEYeuYiEPdva+9N5fO36DuFqa4hbY9tT6Mec9Lv9SJ/w7F0VjGSgwJWn4ad1meuzSnxeaj8XPjwhkf4kvSXUQLZ4WF0ikBUHmPdNP5LXYohkwz3OT0q7bo/PfDem5IdoyGvPT0E0rMLhyNLpIGjoBN7Q4pOvQ5zzz4LiG664mcikdpBA8Uty/mUklt2uaudZIX+VkuOBzGMdMQH7I26gXIVZG7WcJPr9BYCvhYbbaB6W58xaD1+hdwIDAQAB
    #授权回调地址（支付宝授权登录回到地址）
    redirectUrl: https://axktest.caixinsc.com/prod-api/alipay/oauth/callback
    #支付宝网关
    geteWay: https://openapi.alipay.com/gateway.do
    #异步支付通知地址
    notifyUrl: https://axktest.caixinsc.com/prod-api/alipay/hlk/order/notify
    # 页面跳转同步通知页面路径 需http://或者https://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
    #    returnUrl: https://zhbexg.natappfree.cc/alipay/return
    #签名方式
    signType: RSA2
    charset: UTF-8
hfb:
    # 汇付宝公钥
    hfbPublicKey:
    # 商家公钥
    merchPublicKey:
    # 商家私钥
    merchPrivateKey:
    # 汇付宝七位商户号
    hfbMerchantId:
    # 异步通知地址
    payNotifyUrl:
    # 签约通知地址
    signNotifyUrl:
    # 签约返回页面地址
    signReturnUrl:


hfbAliWap:
    # MD5密钥，商户后台网关密钥下面第一个
    key:
    # 商户编号，（汇付宝商户内码：七位整数数字）
    agentId:
    # 异步通知地址
    #  notifyUrl: https://axktest.caixinsc.com/stage-api/hfb/payNotify
    notifyUrl: https://axktest.caixinsc.com/prod-api/hfbAliWap/payNotify
    # 同步通知地址
    #  returnUrl: https://axktest.caixinsc.com/stage-api/hfb/payNotify
    returnUrl: https://axkmbtest.caixinsc.com/pages/me/payStore?orderCode=
