ALTER TABLE order_bill ADD COLUMN pay_channel VARCHAR(32) COMMENT '代扣渠道 ALIPAY JDPAY';
ALTER TABLE order_info ADD COLUMN pay_channel VARCHAR(32) DEFAULT 'ALIPAY' COMMENT '代扣渠道 ALIPAY JDPAY';
ALTER TABLE product_info ADD COLUMN pay_channel VARCHAR(32) DEFAULT 'ALIPAY' COMMENT '代扣渠道 ALIPAY JDPAY';
